### ISSUE TITLE
Simpson's paradox in the regression?

### ISSUE THREAD

**Issue by traceybit** [jcvdav/this_repo#1]
@jcvdav -- Looks like ther emight be a rpoblem in estimatiing... The figure created in the chunk code beninging in [L50](https://github.com/jcvdav/this_repo/blame/master/docs/manuscript.Rmd#L50) each spec..... perhaps we shoudl fit three distinct lines?

**Comment by jcvdav** [comment]
Hey, thaty ssounds about right. Dont have time, can you fix it?
